### ISSUE TITLE
saving and loading off GPUs

### ISSUE THREAD

**Issue by bluebelmont** [neuroailab/ptutils#19]
loading from database is currently slow. this may be due to loading torch tensors that were bound to a specific gpu when they were saved, so we should move them to cpu before saving.

**Comment by bluebelmont** [comment]
tfutils_like_tests is currently not passing, and i think it's because of this issue. when the script is run, this is the resulting stack trace:

` Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "tests/tfutils_like_tests.py", line 19, in <module>
    """
  File "tests/tfutils_like_tests.py", line 180, in test_training
    runner.train()
  File "/home/bsheffer/ptutils/ptutils/runner.py", line 197, in train
    model_output = self.step(model_output)
  File "/home/bsheffer/ptutils/ptutils/runner.py", line 182, in step
    output = self.model.step(data)
  File "/home/bsheffer/ptutils/ptutils/model.py", line 108, in step
    output = self.forward(input)
  File "/home/bsheffer/ptutils/ptutils/model.py", line 84, in forward
    return self.net(input_var)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "tests/tfutils_like_tests.py", line 66, in forward
    out = self.layer1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/conv.py", line 254, in forward
    self.padding, self.dilation, self.groups)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 52, in conv2d
    return f(input, weight, bias)
RuntimeError: tensors are on different GPUs

when trying to access input in pdb,

Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /usr/local/lib/python2.7/dist-packages/torch/nn/functional.py(52)conv2d()
-> return f(input, weight, bias)
(Pdb) input
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorCopy.c line=65 error=77 : an illegal memory access was encountered
*** RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/torch/lib/THC/generic/THCTensorCopy.c:65 `

I believe this is due improper handling of loading/saving and GPUs

**Comment by alexandonian** [comment]
@bluebelmont Is this still an issue, or can it be closed?

**Comment by bluebelmont** [comment]
@alexandonian not unless you've implemented it -- it turns out that my comment was wrong and this was not the cause of the error, so we still need to implement it.

it's implemented for the variables that are attributes of `bases` but not for the tensors in the model (i.e. most)

**Comment by bluebelmont** [comment]
this has been implemented but not thoroughly tested yet

**Comment by bluebelmont** [comment]
fixed in 15899454251b06f26f57c214ef09f5af0cd8e29a.

for reloading model onto a different GPU, changes were made to `Runner._replace_params` to set child devices to `None` if parent devices is specified in `replacement` (see docstring for details)

**Comment by KTFeigelis** [comment]
Changed in _tensor_to_binary to just to tensor.cpu() for all tensors, whether they are in _bases or _params.

Since we will no longer be handling cuda calls for the client, we can freely move everything to CPU before storing in the database.

**Comment by bluebelmont** [comment]
fixed in aba18fef0ac798dea16eb4120d198ddf5fef3f44 now that all of the cuda calls are handled by the user
